use enum_map::Enum;
use livesplit_core::{hotkey::KeyCode, HotkeyConfig};

#[derive(Copy, Clone, Enum)]
pub enum Hotkey {
    Split,
    Reset,
    Undo,
    Skip,
    Pause,
    UndoAllPauses,
    PreviousComparison,
    NextComparison,
    ToggleTimingMethod,
}

impl Hotkey {
    pub fn get_name(self) -> &'static str {
        match self {
            Hotkey::Split => "Split",
            Hotkey::Reset => "Reset",
            Hotkey::Undo => "Undo",
            Hotkey::Skip => "Skip",
            Hotkey::Pause => "Pause",
            Hotkey::UndoAllPauses => "Undo All Pauses",
            Hotkey::PreviousComparison => "Previous Comparison",
            Hotkey::NextComparison => "Next Comparison",
            Hotkey::ToggleTimingMethod => "Toggle Timing Method",
        }
    }

    pub fn get_keycode(self, config: &HotkeyConfig) -> Option<KeyCode> {
        match self {
            Hotkey::Split => config.split,
            Hotkey::Reset => config.reset,
            Hotkey::Undo => config.undo,
            Hotkey::Skip => config.skip,
            Hotkey::Pause => config.pause,
            Hotkey::UndoAllPauses => config.undo_all_pauses,
            Hotkey::PreviousComparison => config.previous_comparison,
            Hotkey::NextComparison => config.next_comparison,
            Hotkey::ToggleTimingMethod => config.toggle_timing_method,
        }
    }

    pub fn set_keycode(self, config: &mut HotkeyConfig, keycode: Option<KeyCode>) {
        match self {
            Hotkey::Split => config.split = keycode,
            Hotkey::Reset => config.reset = keycode,
            Hotkey::Undo => config.undo = keycode,
            Hotkey::Skip => config.skip = keycode,
            Hotkey::Pause => config.pause = keycode,
            Hotkey::UndoAllPauses => config.undo_all_pauses = keycode,
            Hotkey::PreviousComparison => config.previous_comparison = keycode,
            Hotkey::NextComparison => config.next_comparison = keycode,
            Hotkey::ToggleTimingMethod => config.toggle_timing_method = keycode,
        };
    }
}

use KeyCode::*;
// this needs to be updated if livesplit has more keycodes, todo how to make this iteration automatic
pub const KEY_CODES: [KeyCode; 214] = [
    Backquote,
    Backslash,
    Backspace,
    BracketLeft,
    BracketRight,
    Comma,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Equal,
    IntlBackslash,
    IntlRo,
    IntlYen,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,
    // Functional Keys
    AltLeft,
    AltRight,
    CapsLock,
    ContextMenu,
    ControlLeft,
    ControlRight,
    Enter,
    MetaLeft, // Known as OSLeft in all Firefox versions and Chrome <52, as well as all versions of Safari GTK and WPE.
    MetaRight, // Known as OSRight in all Firefox versions and Chrome <52, as well as all versions of Safari GTK and WPE.
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    // Functional Keys found on Japanese and Korean keyboards
    Convert,
    KanaMode,
    Lang1,
    Lang2,
    Lang3,
    Lang4,
    Lang5,
    NonConvert,
    // Control Pad Section
    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,
    // Arrow Pad Section
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    // Numpad Section
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,  // No browser seems to use these?
    NumpadClear,      // No browser seems to use these?
    NumpadClearEntry, // No browser seems to use these?
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadHash,           // No browser seems to use these?
    NumpadMemoryAdd,      // No browser seems to use these?
    NumpadMemoryClear,    // No browser seems to use these?
    NumpadMemoryRecall,   // No browser seems to use these?
    NumpadMemoryStore,    // No browser seems to use these?
    NumpadMemorySubtract, // No browser seems to use these?
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar, // No browser seems to use these?
    NumpadSubtract,
    // Function Section
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Fn,
    FnLock, // No browser seems to use this?
    PrintScreen,
    ScrollLock,
    Pause,
    // Media Keys
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,
    Eject,
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,
    // Legacy, Non-Standard and Special Keys
    Again,
    Copy,
    Cut,
    Find,
    Open,
    Paste,
    Props,
    Select,
    Undo,
    // Gamepad Keys
    Gamepad0,
    Gamepad1,
    Gamepad2,
    Gamepad3,
    Gamepad4,
    Gamepad5,
    Gamepad6,
    Gamepad7,
    Gamepad8,
    Gamepad9,
    Gamepad10,
    Gamepad11,
    Gamepad12,
    Gamepad13,
    Gamepad14,
    Gamepad15,
    Gamepad16,
    Gamepad17,
    Gamepad18,
    Gamepad19,
    // Chrome only Keys
    BrightnessDown,
    BrightnessUp,
    DisplayToggleIntExt,
    KeyboardLayoutSelect,
    LaunchAssistant,
    LaunchControlPanel,
    LaunchScreenSaver,
    MailForward,
    MailReply,
    MailSend,
    MediaFastForward,
    MediaPause,
    MediaPlay,
    MediaRecord,
    MediaRewind,
    PrivacyScreenToggle,
    SelectTask,
    ShowAllWindows,
    ZoomToggle,
];
